name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.CI --tag andremor/dashboard
    - name: Running bot CI script
      run: docker run andremor/dashboard
    - name: See image size
      run: docker images | grep "andremor/dashboard"